// Builds the server, lists its tools through the MCP SDK's in-memory client, and writes
// docs/tools.md. Run with `pnpm docs:tools` (Node type stripping loads src/*.ts).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { ApiClient } from "../src/client/api.ts";
import { silentLogger } from "../src/lib/logger.ts";
import { createServer } from "../src/server.ts";

const OUTPUT = fileURLToPath(new URL("../docs/tools.md", import.meta.url));

const config = {
  apiKey: "sf_pat_docs",
  baseUrl: "https://api.usesuperflow.ai/v1",
  defaultProject: undefined,
  readOnly: false,
  logLevel: "silent",
};
const api = new ApiClient({ apiKey: config.apiKey, baseUrl: config.baseUrl, logger: silentLogger });
const server = createServer({ config, client: api, logger: silentLogger });
const client = new Client({ name: "superflow-mcp-docs", version: "0.0.0" });
const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);

const { tools } = await client.listTools();
const { prompts } = await client.listPrompts();
const { resources } = await client.listResources();
const { resourceTemplates } = await client.listResourceTemplates();
await client.close();
await server.close();

function escapeCell(text) {
  return String(text ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function typeOf(schema) {
  if (!schema || typeof schema !== "object") return "any";
  if (Array.isArray(schema.anyOf)) return schema.anyOf.map(typeOf).join(" or ");
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => `\`${v}\``).join(", ");
  if (schema.type === "array") return `array of ${typeOf(schema.items)}`;
  if (schema.type === "object") {
    const keys = Object.keys(schema.properties ?? {});
    return keys.length ? `object (${keys.join(", ")})` : "object";
  }
  return schema.type ?? "any";
}

function yesNo(value) {
  return value ? "yes" : "no";
}

const lines = [
  "# Tools",
  "",
  "<!-- Generated by `pnpm docs:tools` from the server's tools/list. Do not edit by hand. -->",
  "",
  `superflow-mcp registers ${tools.length} tools. With \`SUPERFLOW_READ_ONLY=true\` only the ${
    tools.filter((t) => t.annotations?.readOnlyHint).length
  } read-only tools are registered.`,
  "",
  "Every id parameter also takes a name, URL, email or number: the API resolves it. Comment numbers need a project, or `SUPERFLOW_DEFAULT_PROJECT`.",
  "",
  "| Tool | Title | Read only | Destructive | Idempotent | Open world |",
  "|---|---|---|---|---|---|",
];
for (const tool of tools) {
  const a = tool.annotations ?? {};
  lines.push(
    `| [\`${tool.name}\`](#${tool.name}) | ${escapeCell(tool.title)} | ${yesNo(a.readOnlyHint)} | ${yesNo(a.destructiveHint)} | ${yesNo(
      a.idempotentHint,
    )} | ${yesNo(a.openWorldHint)} |`,
  );
}
lines.push("");

for (const tool of tools) {
  lines.push(`## ${tool.name}`, "", `**${tool.title}**`, "");
  const description = tool.description ?? "";
  const exampleMatch = /^Example: (.+)$/m.exec(description);
  const prose = description.replace(/^Example: .+$/m, "").trim();
  lines.push(prose, "");
  const properties = tool.inputSchema.properties ?? {};
  const required = new Set(tool.inputSchema.required ?? []);
  const names = Object.keys(properties);
  if (names.length === 0) {
    lines.push("No parameters.", "");
  } else {
    lines.push("| Parameter | Type | Required | Description |", "|---|---|---|---|");
    for (const name of names) {
      const schema = properties[name];
      const fallback = schema.default !== undefined ? ` Default: \`${JSON.stringify(schema.default)}\`.` : "";
      const description = `${schema.description ?? ""}${fallback && !/default/i.test(String(schema.description ?? "")) ? fallback : ""}`;
      lines.push(`| \`${name}\` | ${escapeCell(typeOf(schema))} | ${required.has(name) ? "yes" : "no"} | ${escapeCell(description)} |`);
    }
    lines.push("");
  }
  if (exampleMatch) {
    lines.push("Example:", "", "```json", JSON.stringify(JSON.parse(exampleMatch[1])), "```", "");
  }
}

lines.push("# Prompts", "", "| Prompt | Arguments | Description |", "|---|---|---|");
for (const prompt of prompts) {
  const args = (prompt.arguments ?? []).map((a) => `\`${a.name}\`${a.required ? "" : " (optional)"}`).join(", ");
  lines.push(`| \`${prompt.name}\` | ${args || "none"} | ${escapeCell(prompt.description)} |`);
}
lines.push("", "# Resources", "", "| URI | Description |", "|---|---|");
for (const resource of resources) lines.push(`| \`${resource.uri}\` | ${escapeCell(resource.description)} |`);
for (const template of resourceTemplates) lines.push(`| \`${template.uriTemplate}\` | ${escapeCell(template.description)} |`);
lines.push("");

writeFileSync(OUTPUT, lines.join("\n"));
console.log(`Wrote docs/tools.md (${tools.length} tools, ${prompts.length} prompts, ${resources.length + resourceTemplates.length} resources).`);
